# Generated by Django 5.1.4 on 2026-04-07 13:11

import models.core
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', models.core.HealthcareUserManager()),
            ],
        ),
    ]
